spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nadine?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: racem.messaoudi@gmail.com
    password: vqslyxehzolbwyie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8089
cors:
  authorized:
    client: "*"
